/**
 * One-time export: reads local-dev accounts (users, admins) and their
 * resumes out of the Postgres database this server currently points at
 * (server/.env's DATABASE_URL), and writes a D1-compatible .sql file of
 * `INSERT OR IGNORE` statements to import into the real Cloudflare D1
 * database (worker/).
 *
 * This is a one-time data carry-over, not an ongoing sync — see the
 * project notes: Postgres is being retired in favor of D1 as the real
 * production database, but the local-dev accounts (including the admin
 * account) are worth keeping.
 *
 * Run from server/, on a machine that can actually reach the Postgres
 * host (the sandbox this was written in cannot):
 *
 *   cd server
 *   npx tsx scripts/exportAccountsToD1.ts
 *
 * That writes ../worker/migrations/seed-accounts.sql. Then, from worker/:
 *
 *   npx wrangler d1 execute resumelingo-db --remote --file=./migrations/seed-accounts.sql
 *
 * Notes on the mapping:
 * - D1's `users` table (see worker/migrations/0001_init.sql) has no
 *   stripeCustomerId/stripeSubscriptionId/suspended columns — Stripe
 *   billing and account suspension are still Postgres/server-only
 *   features (Phase 4 of the Cloudflare parity work), so those columns
 *   are simply not exported.
 * - D1's new `admins` table (worker/migrations/0003_admins_table.sql)
 *   matches Postgres's shape exactly, so admins export 1:1.
 * - bcryptjs is used identically by both backends, so passwordHash
 *   values are copied verbatim — no rehashing needed.
 * - Postgres booleans (coverLetterEnabled, recruiterModeEnabled,
 *   combineExperienceFormat, referencesEnabled,
 *   referencesRecruiterModeOnly) are written out as 0/1 for D1/SQLite.
 * - INSERT OR IGNORE is used throughout so this is safe to re-run, or to
 *   run against a D1 database that already has some test accounts in it
 *   (existing rows with the same id/slug/email are left untouched rather
 *   than erroring the whole import out).
 */
import "dotenv/config";
import { writeFileSync } from "fs";
import path from "path";
import { pool } from "../src/db/database";

function sqlString(value: unknown): string {
  if (value === null || value === undefined) return "NULL";
  return `'${String(value).replace(/'/g, "''")}'`;
}

function sqlBool(value: unknown): string {
  return value ? "1" : "0";
}

const USER_COLUMNS = ["id", "name", "email", "passwordHash", "profession", "subscriptionTier", "createdAt"] as const;

const ADMIN_COLUMNS = ["id", "name", "email", "passwordHash", "createdAt"] as const;

const RESUME_COLUMNS = [
  "id",
  "userId",
  "slug",
  "fullName",
  "contactEmail",
  "contactPhone",
  "contactLinkedIn",
  "photoUrl",
  "title",
  "profession",
  "templateKey",
  "visibility",
  "accessPassword",
  "accessPasswordExpiresAt",
  "coverLetterEnabled",
  "generatedCoverLetter",
  "recruiterModeEnabled",
  "recruiterLocation",
  "recruiterAvailability",
  "recruiterClearance",
  "recruiterWorkAuthorization",
  "recruiterExpectedSalary",
  "recruiterRemotePreference",
  "combineExperienceFormat",
  "answers",
  "experience",
  "education",
  "awards",
  "achievements",
  "skillsAndTools",
  "referencesEnabled",
  "references",
  "referencesRecruiterModeOnly",
  "generatedSummary",
  "generatedBullets",
  "viewCount",
  "createdAt",
  "updatedAt",
] as const;

const RESUME_BOOLEAN_COLUMNS = new Set([
  "coverLetterEnabled",
  "recruiterModeEnabled",
  "combineExperienceFormat",
  "referencesEnabled",
  "referencesRecruiterModeOnly",
]);

function insertStatement(table: string, columns: readonly string[], row: Record<string, unknown>, booleanColumns?: Set<string>): string {
  const quotedColumns = columns.map((c) => `"${c}"`).join(", ");
  const values = columns
    .map((c) => {
      const v = row[c];
      if (booleanColumns?.has(c)) return sqlBool(v);
      if (typeof v === "number") return String(v);
      return sqlString(v);
    })
    .join(", ");
  return `INSERT OR IGNORE INTO ${table} (${quotedColumns}) VALUES (${values});`;
}

async function main() {
  const lines: string[] = [
    "-- Generated by server/scripts/exportAccountsToD1.ts — one-time carry-over",
    "-- of local-dev Postgres accounts (users, admins, resumes) into D1.",
    "-- Safe to re-run: every statement is INSERT OR IGNORE.",
    "",
  ];

  const { rows: users } = await pool.query('SELECT * FROM users');
  lines.push(`-- ${users.length} user(s)`);
  for (const row of users) lines.push(insertStatement("users", USER_COLUMNS, row));
  lines.push("");

  const { rows: admins } = await pool.query('SELECT * FROM admins');
  lines.push(`-- ${admins.length} admin(s)`);
  for (const row of admins) lines.push(insertStatement("admins", ADMIN_COLUMNS, row));
  lines.push("");

  const { rows: resumes } = await pool.query('SELECT * FROM resumes');
  lines.push(`-- ${resumes.length} resume(s)`);
  for (const row of resumes) lines.push(insertStatement("resumes", RESUME_COLUMNS, row, RESUME_BOOLEAN_COLUMNS));
  lines.push("");

  const outPath = path.join(__dirname, "..", "..", "worker", "migrations", "seed-accounts.sql");
  writeFileSync(outPath, lines.join("\n"));
  console.log(`Wrote ${outPath}`);
  console.log(`users: ${users.length}, admins: ${admins.length}, resumes: ${resumes.length}`);

  await pool.end();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
